// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "clientId": string;
      "clientSecret": string;
      "ocrLang": string;
      "ocrType": string;
      "cancelBehavior": string;
    };
  }
}
